#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jdk-hawtjni-project
Version  : hawtjni.project.1.10
Release  : 1
URL      : https://github.com/fusesource/hawtjni/archive/hawtjni-project-1.10.tar.gz
Source0  : https://github.com/fusesource/hawtjni/archive/hawtjni-project-1.10.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: jdk-hawtjni-project-data
BuildRequires : apache-maven
BuildRequires : apache-maven2
BuildRequires : javapackages-tools
BuildRequires : jdk-aether
BuildRequires : jdk-aopalliance
BuildRequires : jdk-atinject
BuildRequires : jdk-cdi-api
BuildRequires : jdk-commons-beanutils
BuildRequires : jdk-commons-cli
BuildRequires : jdk-commons-codec
BuildRequires : jdk-commons-collections
BuildRequires : jdk-commons-compress
BuildRequires : jdk-commons-digester
BuildRequires : jdk-commons-io
BuildRequires : jdk-commons-lang
BuildRequires : jdk-commons-lang3
BuildRequires : jdk-commons-logging
BuildRequires : jdk-commons-validator
BuildRequires : jdk-doxia
BuildRequires : jdk-doxia-sitetools
BuildRequires : jdk-fusesource-pom
BuildRequires : jdk-guava
BuildRequires : jdk-guice
BuildRequires : jdk-httpcomponents-client
BuildRequires : jdk-httpcomponents-core
BuildRequires : jdk-jdom
BuildRequires : jdk-jsoup
BuildRequires : jdk-jsr-305
BuildRequires : jdk-jtidy
BuildRequires : jdk-log4j
BuildRequires : jdk-maven-archiver
BuildRequires : jdk-maven-common-artifact-filters
BuildRequires : jdk-maven-compiler-plugin
BuildRequires : jdk-maven-filtering
BuildRequires : jdk-maven-invoker
BuildRequires : jdk-maven-jar-plugin
BuildRequires : jdk-maven-javadoc-plugin
BuildRequires : jdk-maven-plugin-tools
BuildRequires : jdk-maven-reporting-api
BuildRequires : jdk-maven-reporting-impl
BuildRequires : jdk-maven-resources-plugin
BuildRequires : jdk-maven-shared-incremental
BuildRequires : jdk-maven-shared-utils
BuildRequires : jdk-objectweb-asm
BuildRequires : jdk-plexus-archiver
BuildRequires : jdk-plexus-build-api
BuildRequires : jdk-plexus-cipher
BuildRequires : jdk-plexus-classworlds
BuildRequires : jdk-plexus-cli
BuildRequires : jdk-plexus-compiler
BuildRequires : jdk-plexus-containers
BuildRequires : jdk-plexus-i18n
BuildRequires : jdk-plexus-interactivity
BuildRequires : jdk-plexus-interpolation
BuildRequires : jdk-plexus-io
BuildRequires : jdk-plexus-sec-dispatcher
BuildRequires : jdk-plexus-utils
BuildRequires : jdk-plexus-velocity
BuildRequires : jdk-qdox
BuildRequires : jdk-sisu
BuildRequires : jdk-slf4j
BuildRequires : jdk-snappy
BuildRequires : jdk-surefire
BuildRequires : jdk-velocity
BuildRequires : jdk-wagon
BuildRequires : jdk-xbean
BuildRequires : jdk-xmlunit
BuildRequires : jdk-xz
BuildRequires : lxml
BuildRequires : openjdk-dev
BuildRequires : python3
BuildRequires : six
BuildRequires : xmvn
Patch1: 0001-Fix-shading-and-remove-unneeded-modules.patch
Patch2: 0002-Fix-xbean-compatibility.patch
Patch3: 0003-Remove-plexus-maven-plugin-dependency.patch
Patch4: 0004-Remove-eclipse-plugin.patch

%description
HawtJNI
==========
Description
-----------
[HawtJNI][1] is a code generator that produces the JNI code needed to implement java native methods.  It is based on the [jnigen][2] code generator that is part of the SWT Tools
project which is used to generate all the JNI code which powers the eclipse platform.

%package data
Summary: data components for the jdk-hawtjni-project package.
Group: Data

%description data
data components for the jdk-hawtjni-project package.


%prep
%setup -q -n hawtjni-hawtjni-project-1.10
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

python3 /usr/share/java-utils/mvn_package.py ":hawtjni-runtime" runtime
python3 /usr/share/java-utils/mvn_package.py ":maven-hawtjni-plugin" maven-plugin
python3 /usr/share/java-utils/pom_editor.py pom_xpath_set "pom:groupId[text()='asm']" org.ow2.asm hawtjni-generator
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin :maven-javadoc-plugin hawtjni-runtime

%build
python3 /usr/share/java-utils/mvn_build.py

%install
xmvn-install  -R .xmvn-reactor -n hawtjni -d %{buildroot}

%files
%defattr(-,root,root,-)
/usr/lib/java/hawtjni/hawtjni-runtime.jar

%files data
%defattr(-,root,root,-)
/usr/share/java/hawtjni/hawtjni-generator.jar
/usr/share/java/hawtjni/maven-hawtjni-plugin.jar
/usr/share/maven-metadata/hawtjni-maven-plugin.xml
/usr/share/maven-metadata/hawtjni-runtime.xml
/usr/share/maven-metadata/hawtjni.xml
/usr/share/maven-poms/hawtjni/hawtjni-generator.pom
/usr/share/maven-poms/hawtjni/hawtjni-project.pom
/usr/share/maven-poms/hawtjni/hawtjni-runtime.pom
/usr/share/maven-poms/hawtjni/maven-hawtjni-plugin.pom
